def diccionario(idioma):
    traducciones = {
        "Español": {
            "titulo": "🔮 Predicción de mantenimiento de vehículos",
            "ver_manual": "📘 Ver manual de usuario",
            "cerrar_manual": "Cerrar Manual",
            "abrir_manual": "Abrir Manual",
            "modo_entrada": "Selecciona el modo de ingreso de datos:",
            "archivo_csv": "Cargar archivo CSV",
            "entrada_manual": "Entrada manual",
            "subir_csv": "Sube tu archivo CSV",
            "vista_previa": "📄 Vista previa de los datos:",
            "prediccion_modelo": "Hacer Predicción con modelo por defecto",
            "resultados": "🔍 Resultados:",
            "error": "❌ Error en la predicción:",
            "ingreso_manual": "✍️ Ingreso de datos manual",
            "prediccion_exitosa": "✅ {pred:.4f} millas por galón combinados",
            "ver_pdf": "📄 Ver informe PDF",
            "abrir_pdf": "Abrir PDF",
            "cerrar_pdf": "Cerrar PDF",
            "marca":"Marca",
            "modelo":"Modelo",
            "clase":"Clase",
            "transmision":"Transmisión",
            "ano":"Año",
            "cilindros":"Cilindros",
            "cilindrada":"Cilindrada",
            "conduccion":"Conducción",
            "tipo_combustible":"Tipo de combustible",
            "mpg_ciudad":"Millas por galón en ciudad",
            "mpg_carretera":"Millas por galón en carretera",
            "pie_pagina":"📘 Predicción de Mantenimiento de Automóviles",
            "dimensiones": "Dimensiones",
            "memoria_usada": "Memoria usada",
            "tipo_datos": "Tipo de datos:",
            "duplicados": "valores duplicados",
            "matriz_correlacion": "Matriz de correlación",
            "columnas_numericas": "Columnas Numéricas:",
            "columnas_categoricas": "Columnas Categóricas:",
            "faltantes": "{col}: {val} ({pct:.2f}%)",
            "sin_valores_faltantes": "{col}: sin valores faltantes",
            "dist_num":"Distribución de variables numéricas",
            "dist_cat":"Distribución de variables categóricas",
            "sin_valores_faltantes": "sin valores faltantes",
            "resultados_modelos": "Resultados de Modelos entrenados",
            "modelo": "Modelo",
            "precision": "Precisión",
            "mae": "MAE",
            "rmse": "RMSE",
            "r2": "R²",
            "pruebas": "PRUEBAS",
            "pruebas_u_theil": "Pruebas de U de Theil",
            "prueba_anova": "Prueba de ANOVA",
            "distribucion_errores": "Distribución de errores",
        },
        "English": {
            "titulo": "🔮 Vehicle Maintenance Prediction",
            "ver_manual": "📘 View User Manual",
            "cerrar_manual": "Close Manual",
            "abrir_manual": "Open Manual",
            "modo_entrada": "Select the data input mode:",
            "archivo_csv": "Upload CSV file",
            "entrada_manual": "Manual input",
            "subir_csv": "Upload your CSV file",
            "vista_previa": "📄 Data preview:",
            "prediccion_modelo": "Make Prediction with default model",
            "resultados": "🔍 Results:",
            "error": "❌ Prediction error:",
            "ingreso_manual": "✍️ Manual data input",
            "prediccion_exitosa": "✅ {pred:.4f} miles per gallon combined",
            "ver_pdf": "📄 View PDF report",
            "abrir_pdf": "Open PDF",
            "cerrar_pdf": "Close PDF",
            "marca": "Brand",
            "modelo": "Model",
            "clase": "Class",
            "transmision": "Transmission",
            "ano": "Year",
            "cilindros": "Cylinders",
            "cilindrada": "Displacement",
            "conduccion": "Drive type",
            "tipo_combustible": "Fuel type",
            "mpg_ciudad": "Miles per gallon in city",
            "mpg_carretera": "Miles per gallon on highway",
            "pie_pagina": "📘 Car Maintenance Prediction",
            "dimensiones": "Dimensions",
            "memoria_usada": "Memory usage",
            "tipo_datos": "Data types:",
            "duplicados": "duplicated values",
            "matriz_correlacion": "Correlation Matrix",
            "columnas_numericas": "Numerical Columns:",
            "columnas_categoricas": "Categorical Columns:",
            "faltantes": "{col}: {val} ({pct:.2f}%)",
            "sin_valores_faltantes": "{col}: no missing values",
            "dist_num": "Distribution of numerical variables",
            "dist_cat": "Distribution of categorical variables",
            "sin_valores_faltantes": "no missing values",
            "resultados_modelos": "Trained Model Results",
            "modelo": "Model",
            "precision": "Accuracy",
            "mae": "MAE",
            "rmse": "RMSE",
            "r2": "R²",
            "pruebas": "TESTS",
            "pruebas_u_theil": "Theil's U Tests",
            "prueba_anova": "ANOVA Test",
            "distribucion_errores": "Error Distribution",
        },
        "Français": {
            "titulo": "🔮 Prédiction de l'entretien des véhicules",
            "ver_manual": "📘 Voir le manuel d'utilisateur",
            "cerrar_manual": "Fermer le manuel",
            "abrir_manual": "Ouvrir le manuel",
            "modo_entrada": "Sélectionnez le mode de saisie des données :",
            "archivo_csv": "Télécharger un fichier CSV",
            "entrada_manual": "Saisie manuelle",
            "subir_csv": "Téléchargez votre fichier CSV",
            "vista_previa": "📄 Aperçu des données :",
            "prediccion_modelo": "Faire une prédiction avec le modèle par défaut",
            "resultados": "🔍 Résultats :",
            "error": "❌ Erreur lors de la prédiction :",
            "ingreso_manual": "✍️ Saisie manuelle des données",
            "prediccion_exitosa": "✅ {pred:.4f} milles par gallon combinés",
            "ver_pdf": "📄 Voir le rapport PDF",
            "abrir_pdf": "Ouvrir le PDF",
            "cerrar_pdf": "Fermer le PDF",
            "marca": "Marque",
            "modelo": "Modèle",
            "clase": "Classe",
            "transmision": "Transmission",
            "ano": "Année",
            "cilindros": "Cylindres",
            "cilindrada": "Cylindrée",
            "conduccion": "Type de transmission",
            "tipo_combustible": "Type de carburant",
            "mpg_ciudad": "Miles par gallon en ville",
            "mpg_carretera": "Miles par gallon sur autoroute",
            "pie_pagina": "📘 Prédiction de l'entretien automobile",
            "dimensiones": "Dimensions",
            "memoria_usada": "Utilisation de la mémoire",
            "tipo_datos": "Types de données:",
            "duplicados": "valeurs dupliquées",
            "matriz_correlacion": "Matrice de corrélation",
            "columnas_numericas": "Colonnes numériques:",
            "columnas_categoricas": "Colonnes catégoriques:",
            "faltantes": "{col}: {val} ({pct:.2f}%)",
            "sin_valores_faltantes": "{col}: pas de valeurs manquantes",
            "dist_num": "Distribution des variables numériques",
            "dist_cat": "Distribution des variables catégoriques",
            "sin_valores_faltantes": "pas de valeurs manquantes",
            "resultados_modelos": "Résultats des modèles entraînés",
            "modelo": "Modèle",
            "precision": "Précision",
            "mae": "MAE",
            "rmse": "RMSE",
            "r2": "R²",
            "pruebas": "TESTS",
            "pruebas_u_theil": "Tests de U de Theil",
            "prueba_anova": "Test ANOVA",
            "distribucion_errores": "Distribution des erreurs",
        }
    } 
    return traducciones[idioma]
